apiVersion: batch/v1
kind: Job
metadata:
  name: hook2
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    spec:
      containers:
      - name: hello
        image: ubuntu
        command:
          - /bin/sh
          - -c
          - |
            echo "Hello from hook 2"
      restartPolicy: Never
  backoffLimit: 4
